// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/grizli-home/DarkEditorial.tsx": () => import("../components/mockups/grizli-home/DarkEditorial.tsx"),
  "./components/mockups/grizli-home/GraffitiStreet.tsx": () => import("../components/mockups/grizli-home/GraffitiStreet.tsx"),
  "./components/mockups/grizli-home/NeonLime.tsx": () => import("../components/mockups/grizli-home/NeonLime.tsx")
};
